ln -s /home/zsolt/.local/share/Steam /home/zsolt/Truehome/Steam
ln -s /home/zsolt/Downloads /home/zsolt/Truehome/Downloads
ln -s /home/zsolt/SSD /home/zsolt/Truehome/SSD
ln -s /home/zsolt/HDD /home/zsolt/Truehome/HDD
ln -s /home/zsolt/Documents /home/zsolt/Truehome/Documents
ln -s /home/zsolt/Pictures /home/zsolt/Truehome/Pictures
ln -s /home/zsolt/Videos /home/zsolt/Truehome/Videos
ln -s /home/zsolt/productivity /home/zsolt/Truehome/productivity
ln -s /mnt/nfs /home/zsolt/Truehome/Nfs
ln -s /home/zsolt/SSD/games /home/zsolt/Games
ln -s /home/zsolt/Music /home/zsolt/Truehome/Music
ln -s /home/zsolt/.config /home/zsolt/Truehome/.config
ln -s /home/zsolt/.local /home/zsolt/Truehome/.local 
